.MODEL SMALL
.STACK 20
.DATA
EXTRN RES:WORD, ASCII:BYTE
PUBLIC DISP ; Making public
.CODE
DISP PROC NEAR
LEA SI, ASCII ; Procedure to separate digit and
MOV DX, RES ; converting them to ASCII
MOV CX, 04
UP: ROL DX, 4
MOV AX, DX
AND AX, 000FH
CMP AL, 0AH
JC ADD30
ADD AL, 07H
ADD30: ADD AL, 30H
MOV [SI], AL
INC SI
DEC CX
JNZ UP
RET
ENDP
END